# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steven's Code
email: steven@brachyon.com
description: >
  This site is here to show potential employers, recruiters, technical stalkers, or lost souls some of the stuff I've worked on in my semi-professional career as a programmer, developer, and engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _eyewumbo
github_username:  eyewumbo

# Build settings
markdown: kramdown
